// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelf->clock));
    bufp->chgBit(oldp+1,(vlSelf->reset));
    bufp->chgBit(oldp+2,(vlSelf->start));
    bufp->chgBit(oldp+3,(vlSelf->stop));
    bufp->chgBit(oldp+4,(vlSelf->SDA_in));
    bufp->chgBit(oldp+5,(vlSelf->SDA));
    bufp->chgBit(oldp+6,(vlSelf->SCL));
    bufp->chgCData(oldp+7,(vlSelf->LEDs),8);
    bufp->chgBit(oldp+8,(vlSelf->Mini_NPU__DOT__clock));
    bufp->chgBit(oldp+9,(vlSelf->Mini_NPU__DOT__reset));
    bufp->chgBit(oldp+10,(vlSelf->Mini_NPU__DOT__start));
    bufp->chgBit(oldp+11,(vlSelf->Mini_NPU__DOT__stop));
    bufp->chgBit(oldp+12,(vlSelf->Mini_NPU__DOT__SDA_in));
    bufp->chgBit(oldp+13,(vlSelf->Mini_NPU__DOT__SDA));
    bufp->chgBit(oldp+14,(vlSelf->Mini_NPU__DOT__SCL));
    bufp->chgCData(oldp+15,(vlSelf->Mini_NPU__DOT__LEDs),8);
    bufp->chgBit(oldp+16,(vlSelf->Mini_NPU__DOT__write_done));
    bufp->chgBit(oldp+17,(vlSelf->Mini_NPU__DOT__data_ready));
    bufp->chgBit(oldp+18,(vlSelf->Mini_NPU__DOT__read_done));
    bufp->chgBit(oldp+19,(vlSelf->Mini_NPU__DOT__abort));
    bufp->chgBit(oldp+20,(vlSelf->Mini_NPU__DOT__write));
    bufp->chgBit(oldp+21,(vlSelf->Mini_NPU__DOT__poll));
    bufp->chgBit(oldp+22,(vlSelf->Mini_NPU__DOT__data_read));
    bufp->chgBit(oldp+23,(vlSelf->Mini_NPU__DOT__data_avail));
    bufp->chgSData(oldp+24,(vlSelf->Mini_NPU__DOT__X_DATA),16);
    bufp->chgSData(oldp+25,(vlSelf->Mini_NPU__DOT__Y_DATA),16);
    bufp->chgSData(oldp+26,(vlSelf->Mini_NPU__DOT__Z_DATA),16);
    bufp->chgBit(oldp+27,(vlSelf->Mini_NPU__DOT__left_activated));
    bufp->chgBit(oldp+28,(vlSelf->Mini_NPU__DOT__right_activated));
    bufp->chgBit(oldp+29,(vlSelf->Mini_NPU__DOT__back_activated));
    bufp->chgBit(oldp+30,(vlSelf->Mini_NPU__DOT__forward_activated));
    bufp->chgBit(oldp+31,(vlSelf->Mini_NPU__DOT__down_activated));
    bufp->chgBit(oldp+32,(vlSelf->Mini_NPU__DOT__up_activated));
    bufp->chgBit(oldp+33,(vlSelf->Mini_NPU__DOT__left_fired));
    bufp->chgBit(oldp+34,(vlSelf->Mini_NPU__DOT__right_fired));
    bufp->chgBit(oldp+35,(vlSelf->Mini_NPU__DOT__back_fired));
    bufp->chgBit(oldp+36,(vlSelf->Mini_NPU__DOT__forward_fired));
    bufp->chgBit(oldp+37,(vlSelf->Mini_NPU__DOT__down_fired));
    bufp->chgBit(oldp+38,(vlSelf->Mini_NPU__DOT__up_fired));
    bufp->chgCData(oldp+39,(vlSelf->Mini_NPU__DOT__fired_array),8);
    bufp->chgBit(oldp+40,(vlSelf->Mini_NPU__DOT__back__DOT__clock));
    bufp->chgBit(oldp+41,(vlSelf->Mini_NPU__DOT__back__DOT__reset));
    bufp->chgBit(oldp+42,(vlSelf->Mini_NPU__DOT__back__DOT__activated));
    bufp->chgBit(oldp+43,(vlSelf->Mini_NPU__DOT__back__DOT__fire));
    bufp->chgIData(oldp+44,(vlSelf->Mini_NPU__DOT__back__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+45,(vlSelf->Mini_NPU__DOT__back__DOT__cycle_en));
    bufp->chgBit(oldp+46,(vlSelf->Mini_NPU__DOT__back__DOT__cycle_reset));
    bufp->chgBit(oldp+47,(vlSelf->Mini_NPU__DOT__back__DOT__accum_up));
    bufp->chgBit(oldp+48,(vlSelf->Mini_NPU__DOT__back__DOT__accum_down));
    bufp->chgBit(oldp+49,(vlSelf->Mini_NPU__DOT__back__DOT__accum_reset));
    bufp->chgIData(oldp+50,(vlSelf->Mini_NPU__DOT__back__DOT__cycle),24);
    bufp->chgCData(oldp+51,(vlSelf->Mini_NPU__DOT__back__DOT__accum),7);
    bufp->chgBit(oldp+52,(vlSelf->Mini_NPU__DOT__back__DOT__mn_state));
    bufp->chgBit(oldp+53,(vlSelf->Mini_NPU__DOT__back__DOT__mn_nextState));
    bufp->chgBit(oldp+54,(vlSelf->Mini_NPU__DOT__down__DOT__clock));
    bufp->chgBit(oldp+55,(vlSelf->Mini_NPU__DOT__down__DOT__reset));
    bufp->chgBit(oldp+56,(vlSelf->Mini_NPU__DOT__down__DOT__activated));
    bufp->chgBit(oldp+57,(vlSelf->Mini_NPU__DOT__down__DOT__fire));
    bufp->chgIData(oldp+58,(vlSelf->Mini_NPU__DOT__down__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+59,(vlSelf->Mini_NPU__DOT__down__DOT__cycle_en));
    bufp->chgBit(oldp+60,(vlSelf->Mini_NPU__DOT__down__DOT__cycle_reset));
    bufp->chgBit(oldp+61,(vlSelf->Mini_NPU__DOT__down__DOT__accum_up));
    bufp->chgBit(oldp+62,(vlSelf->Mini_NPU__DOT__down__DOT__accum_down));
    bufp->chgBit(oldp+63,(vlSelf->Mini_NPU__DOT__down__DOT__accum_reset));
    bufp->chgIData(oldp+64,(vlSelf->Mini_NPU__DOT__down__DOT__cycle),24);
    bufp->chgCData(oldp+65,(vlSelf->Mini_NPU__DOT__down__DOT__accum),7);
    bufp->chgBit(oldp+66,(vlSelf->Mini_NPU__DOT__down__DOT__mn_state));
    bufp->chgBit(oldp+67,(vlSelf->Mini_NPU__DOT__down__DOT__mn_nextState));
    bufp->chgBit(oldp+68,(vlSelf->Mini_NPU__DOT__forward__DOT__clock));
    bufp->chgBit(oldp+69,(vlSelf->Mini_NPU__DOT__forward__DOT__reset));
    bufp->chgBit(oldp+70,(vlSelf->Mini_NPU__DOT__forward__DOT__activated));
    bufp->chgBit(oldp+71,(vlSelf->Mini_NPU__DOT__forward__DOT__fire));
    bufp->chgIData(oldp+72,(vlSelf->Mini_NPU__DOT__forward__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+73,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle_en));
    bufp->chgBit(oldp+74,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle_reset));
    bufp->chgBit(oldp+75,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_up));
    bufp->chgBit(oldp+76,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_down));
    bufp->chgBit(oldp+77,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_reset));
    bufp->chgIData(oldp+78,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle),24);
    bufp->chgCData(oldp+79,(vlSelf->Mini_NPU__DOT__forward__DOT__accum),7);
    bufp->chgBit(oldp+80,(vlSelf->Mini_NPU__DOT__forward__DOT__mn_state));
    bufp->chgBit(oldp+81,(vlSelf->Mini_NPU__DOT__forward__DOT__mn_nextState));
    bufp->chgBit(oldp+82,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__clock));
    bufp->chgBit(oldp+83,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__reset));
    bufp->chgBit(oldp+84,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__stop));
    bufp->chgBit(oldp+85,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA_in));
    bufp->chgBit(oldp+86,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__write));
    bufp->chgBit(oldp+87,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__poll));
    bufp->chgBit(oldp+88,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_read));
    bufp->chgBit(oldp+89,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA));
    bufp->chgBit(oldp+90,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SCL));
    bufp->chgBit(oldp+91,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__write_done));
    bufp->chgBit(oldp+92,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_ready));
    bufp->chgBit(oldp+93,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__read_done));
    bufp->chgBit(oldp+94,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__abort));
    bufp->chgBit(oldp+95,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_avail));
    bufp->chgSData(oldp+96,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X_DATA),16);
    bufp->chgSData(oldp+97,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y_DATA),16);
    bufp->chgSData(oldp+98,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z_DATA),16);
    bufp->chgBit(oldp+99,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA_out));
    bufp->chgBit(oldp+100,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sda_out_en));
    bufp->chgBit(oldp+101,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SCL_out));
    bufp->chgBit(oldp+102,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__scl_out_en));
    bufp->chgCData(oldp+103,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__ADDR),8);
    bufp->chgCData(oldp+104,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__addr),8);
    bufp->chgCData(oldp+105,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sub_addr),8);
    bufp->chgCData(oldp+106,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sad_w),8);
    bufp->chgCData(oldp+107,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sad_r),8);
    bufp->chgCData(oldp+108,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE_addr),8);
    bufp->chgCData(oldp+109,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__DATAX0_addr),8);
    bufp->chgCData(oldp+110,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__FIFO_CTL_addr),8);
    bufp->chgCData(oldp+111,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__FIFO_DATA),8);
    bufp->chgCData(oldp+112,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE),8);
    bufp->chgCData(oldp+113,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X0_DATA),8);
    bufp->chgCData(oldp+114,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X1_DATA),8);
    bufp->chgCData(oldp+115,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y0_DATA),8);
    bufp->chgCData(oldp+116,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y1_DATA),8);
    bufp->chgCData(oldp+117,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z0_DATA),8);
    bufp->chgCData(oldp+118,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z1_DATA),8);
    bufp->chgCData(oldp+119,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__iteration),2);
    bufp->chgCData(oldp+120,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count),4);
    bufp->chgCData(oldp+121,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count),6);
    bufp->chgBit(oldp+122,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i_up));
    bufp->chgBit(oldp+123,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i_clr));
    bufp->chgBit(oldp+124,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count_en));
    bufp->chgBit(oldp+125,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count_reset));
    bufp->chgBit(oldp+126,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count_en));
    bufp->chgBit(oldp+127,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count_reset));
    bufp->chgBit(oldp+128,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_s));
    bufp->chgBit(oldp+129,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_s));
    bufp->chgBit(oldp+130,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_x0));
    bufp->chgBit(oldp+131,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_x1));
    bufp->chgBit(oldp+132,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_x0));
    bufp->chgBit(oldp+133,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_x1));
    bufp->chgBit(oldp+134,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_y0));
    bufp->chgBit(oldp+135,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_y1));
    bufp->chgBit(oldp+136,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_y0));
    bufp->chgBit(oldp+137,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_y1));
    bufp->chgBit(oldp+138,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_z0));
    bufp->chgBit(oldp+139,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_z1));
    bufp->chgBit(oldp+140,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_z0));
    bufp->chgBit(oldp+141,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_z1));
    bufp->chgBit(oldp+142,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data));
    bufp->chgCData(oldp+143,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i2c_state),4);
    bufp->chgCData(oldp+144,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i2c_nextState),4);
    bufp->chgBit(oldp+145,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__clock));
    bufp->chgBit(oldp+146,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__reset));
    bufp->chgBit(oldp+147,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__en));
    bufp->chgBit(oldp+148,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__shift_clr));
    bufp->chgBit(oldp+149,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__serial_bit));
    bufp->chgCData(oldp+150,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__Q),8);
    bufp->chgBit(oldp+151,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__clock));
    bufp->chgBit(oldp+152,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__reset));
    bufp->chgBit(oldp+153,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__en));
    bufp->chgBit(oldp+154,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__shift_clr));
    bufp->chgBit(oldp+155,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__serial_bit));
    bufp->chgCData(oldp+156,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__Q),8);
    bufp->chgBit(oldp+157,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__clock));
    bufp->chgBit(oldp+158,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__reset));
    bufp->chgBit(oldp+159,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__en));
    bufp->chgBit(oldp+160,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__shift_clr));
    bufp->chgBit(oldp+161,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__serial_bit));
    bufp->chgCData(oldp+162,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__Q),8);
    bufp->chgBit(oldp+163,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__clock));
    bufp->chgBit(oldp+164,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__reset));
    bufp->chgBit(oldp+165,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__en));
    bufp->chgBit(oldp+166,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__shift_clr));
    bufp->chgBit(oldp+167,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__serial_bit));
    bufp->chgCData(oldp+168,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__Q),8);
    bufp->chgBit(oldp+169,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__clock));
    bufp->chgBit(oldp+170,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__reset));
    bufp->chgBit(oldp+171,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__en));
    bufp->chgBit(oldp+172,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__shift_clr));
    bufp->chgBit(oldp+173,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__serial_bit));
    bufp->chgCData(oldp+174,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__Q),8);
    bufp->chgBit(oldp+175,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__clock));
    bufp->chgBit(oldp+176,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__reset));
    bufp->chgBit(oldp+177,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__en));
    bufp->chgBit(oldp+178,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__shift_clr));
    bufp->chgBit(oldp+179,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__serial_bit));
    bufp->chgCData(oldp+180,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__Q),8);
    bufp->chgBit(oldp+181,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__clock));
    bufp->chgBit(oldp+182,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__reset));
    bufp->chgBit(oldp+183,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__en));
    bufp->chgBit(oldp+184,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__shift_clr));
    bufp->chgBit(oldp+185,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__serial_bit));
    bufp->chgCData(oldp+186,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__Q),8);
    bufp->chgBit(oldp+187,(vlSelf->Mini_NPU__DOT__led_c__DOT__clock));
    bufp->chgBit(oldp+188,(vlSelf->Mini_NPU__DOT__led_c__DOT__reset));
    bufp->chgCData(oldp+189,(vlSelf->Mini_NPU__DOT__led_c__DOT__fired_array),8);
    bufp->chgCData(oldp+190,(vlSelf->Mini_NPU__DOT__led_c__DOT__LEDs),8);
    bufp->chgIData(oldp+191,(vlSelf->Mini_NPU__DOT__led_c__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+192,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_done));
    bufp->chgBit(oldp+193,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_down));
    bufp->chgBit(oldp+194,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_reset));
    bufp->chgBit(oldp+195,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_en));
    bufp->chgBit(oldp+196,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_reset));
    bufp->chgBit(oldp+197,(vlSelf->Mini_NPU__DOT__led_c__DOT__fired_clr));
    bufp->chgIData(oldp+198,(vlSelf->Mini_NPU__DOT__led_c__DOT__count),25);
    bufp->chgBit(oldp+199,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_state));
    bufp->chgBit(oldp+200,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_nextState));
    bufp->chgBit(oldp+201,(vlSelf->Mini_NPU__DOT__left__DOT__clock));
    bufp->chgBit(oldp+202,(vlSelf->Mini_NPU__DOT__left__DOT__reset));
    bufp->chgBit(oldp+203,(vlSelf->Mini_NPU__DOT__left__DOT__activated));
    bufp->chgBit(oldp+204,(vlSelf->Mini_NPU__DOT__left__DOT__fire));
    bufp->chgIData(oldp+205,(vlSelf->Mini_NPU__DOT__left__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+206,(vlSelf->Mini_NPU__DOT__left__DOT__cycle_en));
    bufp->chgBit(oldp+207,(vlSelf->Mini_NPU__DOT__left__DOT__cycle_reset));
    bufp->chgBit(oldp+208,(vlSelf->Mini_NPU__DOT__left__DOT__accum_up));
    bufp->chgBit(oldp+209,(vlSelf->Mini_NPU__DOT__left__DOT__accum_down));
    bufp->chgBit(oldp+210,(vlSelf->Mini_NPU__DOT__left__DOT__accum_reset));
    bufp->chgIData(oldp+211,(vlSelf->Mini_NPU__DOT__left__DOT__cycle),24);
    bufp->chgCData(oldp+212,(vlSelf->Mini_NPU__DOT__left__DOT__accum),7);
    bufp->chgBit(oldp+213,(vlSelf->Mini_NPU__DOT__left__DOT__mn_state));
    bufp->chgBit(oldp+214,(vlSelf->Mini_NPU__DOT__left__DOT__mn_nextState));
    bufp->chgBit(oldp+215,(vlSelf->Mini_NPU__DOT__ph__DOT__clock));
    bufp->chgBit(oldp+216,(vlSelf->Mini_NPU__DOT__ph__DOT__reset));
    bufp->chgBit(oldp+217,(vlSelf->Mini_NPU__DOT__ph__DOT__start));
    bufp->chgBit(oldp+218,(vlSelf->Mini_NPU__DOT__ph__DOT__stop));
    bufp->chgBit(oldp+219,(vlSelf->Mini_NPU__DOT__ph__DOT__write_done));
    bufp->chgBit(oldp+220,(vlSelf->Mini_NPU__DOT__ph__DOT__data_ready));
    bufp->chgBit(oldp+221,(vlSelf->Mini_NPU__DOT__ph__DOT__read_done));
    bufp->chgBit(oldp+222,(vlSelf->Mini_NPU__DOT__ph__DOT__abort));
    bufp->chgBit(oldp+223,(vlSelf->Mini_NPU__DOT__ph__DOT__write));
    bufp->chgBit(oldp+224,(vlSelf->Mini_NPU__DOT__ph__DOT__poll));
    bufp->chgBit(oldp+225,(vlSelf->Mini_NPU__DOT__ph__DOT__data_read));
    bufp->chgBit(oldp+226,(vlSelf->Mini_NPU__DOT__ph__DOT__write_en));
    bufp->chgBit(oldp+227,(vlSelf->Mini_NPU__DOT__ph__DOT__poll_en));
    bufp->chgBit(oldp+228,(vlSelf->Mini_NPU__DOT__ph__DOT__data_read_en));
    bufp->chgCData(oldp+229,(vlSelf->Mini_NPU__DOT__ph__DOT__ph_state),2);
    bufp->chgCData(oldp+230,(vlSelf->Mini_NPU__DOT__ph__DOT__ph_nextState),2);
    bufp->chgBit(oldp+231,(vlSelf->Mini_NPU__DOT__right__DOT__clock));
    bufp->chgBit(oldp+232,(vlSelf->Mini_NPU__DOT__right__DOT__reset));
    bufp->chgBit(oldp+233,(vlSelf->Mini_NPU__DOT__right__DOT__activated));
    bufp->chgBit(oldp+234,(vlSelf->Mini_NPU__DOT__right__DOT__fire));
    bufp->chgIData(oldp+235,(vlSelf->Mini_NPU__DOT__right__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+236,(vlSelf->Mini_NPU__DOT__right__DOT__cycle_en));
    bufp->chgBit(oldp+237,(vlSelf->Mini_NPU__DOT__right__DOT__cycle_reset));
    bufp->chgBit(oldp+238,(vlSelf->Mini_NPU__DOT__right__DOT__accum_up));
    bufp->chgBit(oldp+239,(vlSelf->Mini_NPU__DOT__right__DOT__accum_down));
    bufp->chgBit(oldp+240,(vlSelf->Mini_NPU__DOT__right__DOT__accum_reset));
    bufp->chgIData(oldp+241,(vlSelf->Mini_NPU__DOT__right__DOT__cycle),24);
    bufp->chgCData(oldp+242,(vlSelf->Mini_NPU__DOT__right__DOT__accum),7);
    bufp->chgBit(oldp+243,(vlSelf->Mini_NPU__DOT__right__DOT__mn_state));
    bufp->chgBit(oldp+244,(vlSelf->Mini_NPU__DOT__right__DOT__mn_nextState));
    bufp->chgBit(oldp+245,(vlSelf->Mini_NPU__DOT__up__DOT__clock));
    bufp->chgBit(oldp+246,(vlSelf->Mini_NPU__DOT__up__DOT__reset));
    bufp->chgBit(oldp+247,(vlSelf->Mini_NPU__DOT__up__DOT__activated));
    bufp->chgBit(oldp+248,(vlSelf->Mini_NPU__DOT__up__DOT__fire));
    bufp->chgIData(oldp+249,(vlSelf->Mini_NPU__DOT__up__DOT__CLK_FRQ),24);
    bufp->chgBit(oldp+250,(vlSelf->Mini_NPU__DOT__up__DOT__cycle_en));
    bufp->chgBit(oldp+251,(vlSelf->Mini_NPU__DOT__up__DOT__cycle_reset));
    bufp->chgBit(oldp+252,(vlSelf->Mini_NPU__DOT__up__DOT__accum_up));
    bufp->chgBit(oldp+253,(vlSelf->Mini_NPU__DOT__up__DOT__accum_down));
    bufp->chgBit(oldp+254,(vlSelf->Mini_NPU__DOT__up__DOT__accum_reset));
    bufp->chgIData(oldp+255,(vlSelf->Mini_NPU__DOT__up__DOT__cycle),24);
    bufp->chgCData(oldp+256,(vlSelf->Mini_NPU__DOT__up__DOT__accum),7);
    bufp->chgBit(oldp+257,(vlSelf->Mini_NPU__DOT__up__DOT__mn_state));
    bufp->chgBit(oldp+258,(vlSelf->Mini_NPU__DOT__up__DOT__mn_nextState));
    bufp->chgBit(oldp+259,(vlSelf->Mini_NPU__DOT__x_axis__DOT__clock));
    bufp->chgBit(oldp+260,(vlSelf->Mini_NPU__DOT__x_axis__DOT__reset));
    bufp->chgBit(oldp+261,(vlSelf->Mini_NPU__DOT__x_axis__DOT__stop));
    bufp->chgBit(oldp+262,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data_avail));
    bufp->chgBit(oldp+263,(vlSelf->Mini_NPU__DOT__x_axis__DOT__abort));
    bufp->chgSData(oldp+264,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data),16);
    bufp->chgBit(oldp+265,(vlSelf->Mini_NPU__DOT__x_axis__DOT__activate1));
    bufp->chgBit(oldp+266,(vlSelf->Mini_NPU__DOT__x_axis__DOT__activate2));
    bufp->chgBit(oldp+267,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AltB));
    bufp->chgBit(oldp+268,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AeqB));
    bufp->chgBit(oldp+269,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AgtB));
    bufp->chgBit(oldp+270,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d1_en));
    bufp->chgBit(oldp+271,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2_en));
    bufp->chgBit(oldp+272,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2n_en));
    bufp->chgBit(oldp+273,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d1_clr));
    bufp->chgBit(oldp+274,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2_clr));
    bufp->chgBit(oldp+275,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2n_clr));
    bufp->chgSData(oldp+276,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data1),16);
    bufp->chgSData(oldp+277,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data2),16);
    bufp->chgSData(oldp+278,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data2_next),16);
    bufp->chgCData(oldp+279,(vlSelf->Mini_NPU__DOT__x_axis__DOT__an_state),3);
    bufp->chgCData(oldp+280,(vlSelf->Mini_NPU__DOT__x_axis__DOT__an_nextState),3);
    bufp->chgBit(oldp+281,(vlSelf->Mini_NPU__DOT__y_axis__DOT__clock));
    bufp->chgBit(oldp+282,(vlSelf->Mini_NPU__DOT__y_axis__DOT__reset));
    bufp->chgBit(oldp+283,(vlSelf->Mini_NPU__DOT__y_axis__DOT__stop));
    bufp->chgBit(oldp+284,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data_avail));
    bufp->chgBit(oldp+285,(vlSelf->Mini_NPU__DOT__y_axis__DOT__abort));
    bufp->chgSData(oldp+286,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data),16);
    bufp->chgBit(oldp+287,(vlSelf->Mini_NPU__DOT__y_axis__DOT__activate1));
    bufp->chgBit(oldp+288,(vlSelf->Mini_NPU__DOT__y_axis__DOT__activate2));
    bufp->chgBit(oldp+289,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AltB));
    bufp->chgBit(oldp+290,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AeqB));
    bufp->chgBit(oldp+291,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AgtB));
    bufp->chgBit(oldp+292,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d1_en));
    bufp->chgBit(oldp+293,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2_en));
    bufp->chgBit(oldp+294,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2n_en));
    bufp->chgBit(oldp+295,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d1_clr));
    bufp->chgBit(oldp+296,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2_clr));
    bufp->chgBit(oldp+297,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2n_clr));
    bufp->chgSData(oldp+298,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data1),16);
    bufp->chgSData(oldp+299,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data2),16);
    bufp->chgSData(oldp+300,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data2_next),16);
    bufp->chgCData(oldp+301,(vlSelf->Mini_NPU__DOT__y_axis__DOT__an_state),3);
    bufp->chgCData(oldp+302,(vlSelf->Mini_NPU__DOT__y_axis__DOT__an_nextState),3);
    bufp->chgBit(oldp+303,(vlSelf->Mini_NPU__DOT__z_axis__DOT__clock));
    bufp->chgBit(oldp+304,(vlSelf->Mini_NPU__DOT__z_axis__DOT__reset));
    bufp->chgBit(oldp+305,(vlSelf->Mini_NPU__DOT__z_axis__DOT__stop));
    bufp->chgBit(oldp+306,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data_avail));
    bufp->chgBit(oldp+307,(vlSelf->Mini_NPU__DOT__z_axis__DOT__abort));
    bufp->chgSData(oldp+308,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data),16);
    bufp->chgBit(oldp+309,(vlSelf->Mini_NPU__DOT__z_axis__DOT__activate1));
    bufp->chgBit(oldp+310,(vlSelf->Mini_NPU__DOT__z_axis__DOT__activate2));
    bufp->chgBit(oldp+311,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AltB));
    bufp->chgBit(oldp+312,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AeqB));
    bufp->chgBit(oldp+313,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AgtB));
    bufp->chgBit(oldp+314,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d1_en));
    bufp->chgBit(oldp+315,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2_en));
    bufp->chgBit(oldp+316,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2n_en));
    bufp->chgBit(oldp+317,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d1_clr));
    bufp->chgBit(oldp+318,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2_clr));
    bufp->chgBit(oldp+319,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2n_clr));
    bufp->chgSData(oldp+320,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data1),16);
    bufp->chgSData(oldp+321,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data2),16);
    bufp->chgSData(oldp+322,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data2_next),16);
    bufp->chgCData(oldp+323,(vlSelf->Mini_NPU__DOT__z_axis__DOT__an_state),3);
    bufp->chgCData(oldp+324,(vlSelf->Mini_NPU__DOT__z_axis__DOT__an_nextState),3);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
