// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(start,0,0);
        VL_IN8(stop,0,0);
        VL_IN8(SDA_in,0,0);
        VL_INOUT8(SDA,0,0);
        VL_OUT8(SCL,0,0);
        VL_OUT8(LEDs,7,0);
        CData/*0:0*/ Mini_NPU__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__start;
        CData/*0:0*/ Mini_NPU__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__SDA_in;
        CData/*0:0*/ Mini_NPU__DOT__SDA;
        CData/*0:0*/ Mini_NPU__DOT__SCL;
        CData/*7:0*/ Mini_NPU__DOT__LEDs;
        CData/*0:0*/ Mini_NPU__DOT__write_done;
        CData/*0:0*/ Mini_NPU__DOT__data_ready;
        CData/*0:0*/ Mini_NPU__DOT__read_done;
        CData/*0:0*/ Mini_NPU__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__write;
        CData/*0:0*/ Mini_NPU__DOT__poll;
        CData/*0:0*/ Mini_NPU__DOT__data_read;
        CData/*0:0*/ Mini_NPU__DOT__data_avail;
        CData/*0:0*/ Mini_NPU__DOT__left_activated;
        CData/*0:0*/ Mini_NPU__DOT__right_activated;
        CData/*0:0*/ Mini_NPU__DOT__back_activated;
        CData/*0:0*/ Mini_NPU__DOT__forward_activated;
        CData/*0:0*/ Mini_NPU__DOT__down_activated;
        CData/*0:0*/ Mini_NPU__DOT__up_activated;
        CData/*0:0*/ Mini_NPU__DOT__left_fired;
        CData/*0:0*/ Mini_NPU__DOT__right_fired;
        CData/*0:0*/ Mini_NPU__DOT__back_fired;
        CData/*0:0*/ Mini_NPU__DOT__forward_fired;
        CData/*0:0*/ Mini_NPU__DOT__down_fired;
        CData/*0:0*/ Mini_NPU__DOT__up_fired;
        CData/*7:0*/ Mini_NPU__DOT__fired_array;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__start;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__write_done;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__data_ready;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__read_done;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__write;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__poll;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__data_read;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__write_en;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__poll_en;
        CData/*0:0*/ Mini_NPU__DOT__ph__DOT__data_read_en;
        CData/*1:0*/ Mini_NPU__DOT__ph__DOT__ph_state;
        CData/*1:0*/ Mini_NPU__DOT__ph__DOT__ph_nextState;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__SDA_in;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__write;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__poll;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data_read;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__SDA;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__SCL;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__write_done;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data_ready;
    };
    struct {
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__read_done;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data_avail;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__SDA_out;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sda_out_en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__SCL_out;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__scl_out_en;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__ADDR;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__addr;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sub_addr;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sad_w;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sad_r;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE_addr;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__DATAX0_addr;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__FIFO_CTL_addr;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__FIFO_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__X0_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__X1_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__Y0_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__Y1_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__Z0_DATA;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__Z1_DATA;
        CData/*1:0*/ Mini_NPU__DOT__i2c_m__DOT__iteration;
        CData/*3:0*/ Mini_NPU__DOT__i2c_m__DOT__count;
        CData/*5:0*/ Mini_NPU__DOT__i2c_m__DOT__data_count;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__i_up;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__i_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__count_en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__count_reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data_count_en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data_count_reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_s;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_s;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_x0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_x1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_x0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_x1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_y0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_y1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_y0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_y1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_z0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_in_z1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_z0;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__shift_clr_z1;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__data;
        CData/*3:0*/ Mini_NPU__DOT__i2c_m__DOT__i2c_state;
        CData/*3:0*/ Mini_NPU__DOT__i2c_m__DOT__i2c_nextState;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__en;
    };
    struct {
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__en;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__shift_clr;
        CData/*0:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__serial_bit;
        CData/*7:0*/ Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__Q;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__data_avail;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__activate1;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__activate2;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__AltB;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__AeqB;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__AgtB;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d1_en;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d2_en;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d2n_en;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d1_clr;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d2_clr;
        CData/*0:0*/ Mini_NPU__DOT__x_axis__DOT__d2n_clr;
        CData/*2:0*/ Mini_NPU__DOT__x_axis__DOT__an_state;
        CData/*2:0*/ Mini_NPU__DOT__x_axis__DOT__an_nextState;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__data_avail;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__activate1;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__activate2;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__AltB;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__AeqB;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__AgtB;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d1_en;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d2_en;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d2n_en;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d1_clr;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d2_clr;
        CData/*0:0*/ Mini_NPU__DOT__y_axis__DOT__d2n_clr;
        CData/*2:0*/ Mini_NPU__DOT__y_axis__DOT__an_state;
        CData/*2:0*/ Mini_NPU__DOT__y_axis__DOT__an_nextState;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__clock;
    };
    struct {
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__stop;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__data_avail;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__abort;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__activate1;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__activate2;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__AltB;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__AeqB;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__AgtB;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d1_en;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d2_en;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d2n_en;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d1_clr;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d2_clr;
        CData/*0:0*/ Mini_NPU__DOT__z_axis__DOT__d2n_clr;
        CData/*2:0*/ Mini_NPU__DOT__z_axis__DOT__an_state;
        CData/*2:0*/ Mini_NPU__DOT__z_axis__DOT__an_nextState;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__left__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__mn_state;
        CData/*0:0*/ Mini_NPU__DOT__left__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__right__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__mn_state;
        CData/*0:0*/ Mini_NPU__DOT__right__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__back__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__mn_state;
        CData/*0:0*/ Mini_NPU__DOT__back__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__forward__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__mn_state;
    };
    struct {
        CData/*0:0*/ Mini_NPU__DOT__forward__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__down__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__mn_state;
        CData/*0:0*/ Mini_NPU__DOT__down__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__reset;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__activated;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__fire;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__cycle_en;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__cycle_reset;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__accum_up;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__accum_down;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__accum_reset;
        CData/*6:0*/ Mini_NPU__DOT__up__DOT__accum;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__mn_state;
        CData/*0:0*/ Mini_NPU__DOT__up__DOT__mn_nextState;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__clock;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__reset;
        CData/*7:0*/ Mini_NPU__DOT__led_c__DOT__fired_array;
        CData/*7:0*/ Mini_NPU__DOT__led_c__DOT__LEDs;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__count_done;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__count_down;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__count_reset;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__led_en;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__led_reset;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__fired_clr;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__led_state;
        CData/*0:0*/ Mini_NPU__DOT__led_c__DOT__led_nextState;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ Mini_NPU__DOT__X_DATA;
        SData/*15:0*/ Mini_NPU__DOT__Y_DATA;
        SData/*15:0*/ Mini_NPU__DOT__Z_DATA;
        SData/*15:0*/ Mini_NPU__DOT__i2c_m__DOT__X_DATA;
        SData/*15:0*/ Mini_NPU__DOT__i2c_m__DOT__Y_DATA;
        SData/*15:0*/ Mini_NPU__DOT__i2c_m__DOT__Z_DATA;
        SData/*15:0*/ Mini_NPU__DOT__x_axis__DOT__data;
        SData/*15:0*/ Mini_NPU__DOT__x_axis__DOT__data1;
        SData/*15:0*/ Mini_NPU__DOT__x_axis__DOT__data2;
        SData/*15:0*/ Mini_NPU__DOT__x_axis__DOT__data2_next;
        SData/*15:0*/ Mini_NPU__DOT__y_axis__DOT__data;
        SData/*15:0*/ Mini_NPU__DOT__y_axis__DOT__data1;
        SData/*15:0*/ Mini_NPU__DOT__y_axis__DOT__data2;
        SData/*15:0*/ Mini_NPU__DOT__y_axis__DOT__data2_next;
        SData/*15:0*/ Mini_NPU__DOT__z_axis__DOT__data;
        SData/*15:0*/ Mini_NPU__DOT__z_axis__DOT__data1;
        SData/*15:0*/ Mini_NPU__DOT__z_axis__DOT__data2;
        SData/*15:0*/ Mini_NPU__DOT__z_axis__DOT__data2_next;
        IData/*23:0*/ Mini_NPU__DOT__left__DOT__CLK_FRQ;
        IData/*23:0*/ Mini_NPU__DOT__left__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__right__DOT__CLK_FRQ;
        IData/*23:0*/ Mini_NPU__DOT__right__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__back__DOT__CLK_FRQ;
    };
    struct {
        IData/*23:0*/ Mini_NPU__DOT__back__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__forward__DOT__CLK_FRQ;
        IData/*23:0*/ Mini_NPU__DOT__forward__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__down__DOT__CLK_FRQ;
        IData/*23:0*/ Mini_NPU__DOT__down__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__up__DOT__CLK_FRQ;
        IData/*23:0*/ Mini_NPU__DOT__up__DOT__cycle;
        IData/*23:0*/ Mini_NPU__DOT__led_c__DOT__CLK_FRQ;
        IData/*24:0*/ Mini_NPU__DOT__led_c__DOT__count;
        IData/*31:0*/ __VactIterCount;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
