// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_Mini_NPU);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__back);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__down);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__forward);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__i2c_m);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__led_c);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__left);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__ph);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__right);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__up);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__x_axis);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__y_axis);
    __Vhier.remove(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__z_axis);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_source);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_x0);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_x1);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_y0);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_y1);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_z0);
    __Vhier.remove(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_z1);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_Mini_NPU.configure(this, name(), "Mini_NPU", "Mini_NPU", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__back.configure(this, name(), "Mini_NPU.back", "back", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__down.configure(this, name(), "Mini_NPU.down", "down", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__forward.configure(this, name(), "Mini_NPU.forward", "forward", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m.configure(this, name(), "Mini_NPU.i2c_m", "i2c_m", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_source.configure(this, name(), "Mini_NPU.i2c_m.sipo_source", "sipo_source", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_x0.configure(this, name(), "Mini_NPU.i2c_m.sipo_x0", "sipo_x0", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_x1.configure(this, name(), "Mini_NPU.i2c_m.sipo_x1", "sipo_x1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_y0.configure(this, name(), "Mini_NPU.i2c_m.sipo_y0", "sipo_y0", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_y1.configure(this, name(), "Mini_NPU.i2c_m.sipo_y1", "sipo_y1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_z0.configure(this, name(), "Mini_NPU.i2c_m.sipo_z0", "sipo_z0", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__i2c_m__sipo_z1.configure(this, name(), "Mini_NPU.i2c_m.sipo_z1", "sipo_z1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__led_c.configure(this, name(), "Mini_NPU.led_c", "led_c", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__left.configure(this, name(), "Mini_NPU.left", "left", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__ph.configure(this, name(), "Mini_NPU.ph", "ph", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__right.configure(this, name(), "Mini_NPU.right", "right", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__up.configure(this, name(), "Mini_NPU.up", "up", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__x_axis.configure(this, name(), "Mini_NPU.x_axis", "x_axis", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__y_axis.configure(this, name(), "Mini_NPU.y_axis", "y_axis", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Mini_NPU__z_axis.configure(this, name(), "Mini_NPU.z_axis", "z_axis", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_Mini_NPU);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__back);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__down);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__forward);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__i2c_m);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__led_c);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__left);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__ph);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__right);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__up);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__x_axis);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__y_axis);
    __Vhier.add(&__Vscope_Mini_NPU, &__Vscope_Mini_NPU__z_axis);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_source);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_x0);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_x1);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_y0);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_y1);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_z0);
    __Vhier.add(&__Vscope_Mini_NPU__i2c_m, &__Vscope_Mini_NPU__i2c_m__sipo_z1);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_Mini_NPU.varInsert(__Vfinal,"LEDs", &(TOP.Mini_NPU__DOT__LEDs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"SCL", &(TOP.Mini_NPU__DOT__SCL), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"SDA", &(TOP.Mini_NPU__DOT__SDA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"SDA_in", &(TOP.Mini_NPU__DOT__SDA_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"X_DATA", &(TOP.Mini_NPU__DOT__X_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"Y_DATA", &(TOP.Mini_NPU__DOT__Y_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"Z_DATA", &(TOP.Mini_NPU__DOT__Z_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"back_activated", &(TOP.Mini_NPU__DOT__back_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"back_fired", &(TOP.Mini_NPU__DOT__back_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"data_avail", &(TOP.Mini_NPU__DOT__data_avail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"data_read", &(TOP.Mini_NPU__DOT__data_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"data_ready", &(TOP.Mini_NPU__DOT__data_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"down_activated", &(TOP.Mini_NPU__DOT__down_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"down_fired", &(TOP.Mini_NPU__DOT__down_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"fired_array", &(TOP.Mini_NPU__DOT__fired_array), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"forward_activated", &(TOP.Mini_NPU__DOT__forward_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"forward_fired", &(TOP.Mini_NPU__DOT__forward_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"left_activated", &(TOP.Mini_NPU__DOT__left_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"left_fired", &(TOP.Mini_NPU__DOT__left_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"poll", &(TOP.Mini_NPU__DOT__poll), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"read_done", &(TOP.Mini_NPU__DOT__read_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"right_activated", &(TOP.Mini_NPU__DOT__right_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"right_fired", &(TOP.Mini_NPU__DOT__right_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"start", &(TOP.Mini_NPU__DOT__start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"up_activated", &(TOP.Mini_NPU__DOT__up_activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"up_fired", &(TOP.Mini_NPU__DOT__up_fired), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"write", &(TOP.Mini_NPU__DOT__write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU.varInsert(__Vfinal,"write_done", &(TOP.Mini_NPU__DOT__write_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__back__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__back__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__back__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__back__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__back__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__back__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__back__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__back__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__back__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__back__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__back__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__back__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__back__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__back.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__back__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__down__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__down__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__down__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__down__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__down__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__down__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__down__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__down__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__down__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__down__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__down__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__down__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__down__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__down.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__down__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__forward__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__forward__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__forward__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__forward__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__forward__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__forward__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__forward__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__forward__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__forward__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__forward__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__forward__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__forward__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__forward__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__forward.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__forward__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"ADDR", &(TOP.Mini_NPU__DOT__i2c_m__DOT__ADDR), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"DATAX0_addr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__DATAX0_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"FIFO_CTL_addr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__FIFO_CTL_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"FIFO_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__FIFO_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"INT_SOURCE", &(TOP.Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"INT_SOURCE_addr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"SCL", &(TOP.Mini_NPU__DOT__i2c_m__DOT__SCL), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"SCL_out", &(TOP.Mini_NPU__DOT__i2c_m__DOT__SCL_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"SDA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__SDA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"SDA_in", &(TOP.Mini_NPU__DOT__i2c_m__DOT__SDA_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"SDA_out", &(TOP.Mini_NPU__DOT__i2c_m__DOT__SDA_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"X0_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__X0_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"X1_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__X1_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"X_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__X_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Y0_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Y0_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Y1_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Y1_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Y_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Y_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Z0_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Z0_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Z1_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Z1_DATA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"Z_DATA", &(TOP.Mini_NPU__DOT__i2c_m__DOT__Z_DATA), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__i2c_m__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"addr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"count", &(TOP.Mini_NPU__DOT__i2c_m__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"count_en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__count_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"count_reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__count_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_avail", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_avail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_count", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_count_en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_count_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_count_reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_count_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_read", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"data_ready", &(TOP.Mini_NPU__DOT__i2c_m__DOT__data_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"i2c_nextState", &(TOP.Mini_NPU__DOT__i2c_m__DOT__i2c_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"i2c_state", &(TOP.Mini_NPU__DOT__i2c_m__DOT__i2c_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"i_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__i_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"i_up", &(TOP.Mini_NPU__DOT__i2c_m__DOT__i_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"iteration", &(TOP.Mini_NPU__DOT__i2c_m__DOT__iteration), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"poll", &(TOP.Mini_NPU__DOT__i2c_m__DOT__poll), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"read_done", &(TOP.Mini_NPU__DOT__i2c_m__DOT__read_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"sad_r", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sad_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"sad_w", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sad_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"scl_out_en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__scl_out_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"sda_out_en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sda_out_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_s", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_x0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_x0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_x1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_x1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_y0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_y0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_y1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_y1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_z0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_z0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_clr_z1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_clr_z1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_s", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_x0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_x0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_x1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_x1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_y0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_y0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_y1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_y1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_z0", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_z0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"shift_in_z1", &(TOP.Mini_NPU__DOT__i2c_m__DOT__shift_in_z1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__i2c_m__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"sub_addr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sub_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"write", &(TOP.Mini_NPU__DOT__i2c_m__DOT__write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m.varInsert(__Vfinal,"write_done", &(TOP.Mini_NPU__DOT__i2c_m__DOT__write_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_source.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x0.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_x1.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y0.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_y1.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z0.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"Q", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"en", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"serial_bit", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__serial_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__i2c_m__sipo_z1.varInsert(__Vfinal,"shift_clr", &(TOP.Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__shift_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__led_c__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"LEDs", &(TOP.Mini_NPU__DOT__led_c__DOT__LEDs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__led_c__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"count", &(TOP.Mini_NPU__DOT__led_c__DOT__count), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,24,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"count_done", &(TOP.Mini_NPU__DOT__led_c__DOT__count_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"count_down", &(TOP.Mini_NPU__DOT__led_c__DOT__count_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"count_reset", &(TOP.Mini_NPU__DOT__led_c__DOT__count_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"fired_array", &(TOP.Mini_NPU__DOT__led_c__DOT__fired_array), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"fired_clr", &(TOP.Mini_NPU__DOT__led_c__DOT__fired_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"led_en", &(TOP.Mini_NPU__DOT__led_c__DOT__led_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"led_nextState", &(TOP.Mini_NPU__DOT__led_c__DOT__led_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"led_reset", &(TOP.Mini_NPU__DOT__led_c__DOT__led_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"led_state", &(TOP.Mini_NPU__DOT__led_c__DOT__led_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__led_c.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__led_c__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__left__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__left__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__left__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__left__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__left__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__left__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__left__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__left__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__left__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__left__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__left__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__left__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__left__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__left.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__left__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__ph__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__ph__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"data_read", &(TOP.Mini_NPU__DOT__ph__DOT__data_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"data_read_en", &(TOP.Mini_NPU__DOT__ph__DOT__data_read_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"data_ready", &(TOP.Mini_NPU__DOT__ph__DOT__data_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"ph_nextState", &(TOP.Mini_NPU__DOT__ph__DOT__ph_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"ph_state", &(TOP.Mini_NPU__DOT__ph__DOT__ph_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"poll", &(TOP.Mini_NPU__DOT__ph__DOT__poll), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"poll_en", &(TOP.Mini_NPU__DOT__ph__DOT__poll_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"read_done", &(TOP.Mini_NPU__DOT__ph__DOT__read_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__ph__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"start", &(TOP.Mini_NPU__DOT__ph__DOT__start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__ph__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"write", &(TOP.Mini_NPU__DOT__ph__DOT__write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"write_done", &(TOP.Mini_NPU__DOT__ph__DOT__write_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__ph.varInsert(__Vfinal,"write_en", &(TOP.Mini_NPU__DOT__ph__DOT__write_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__right__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__right__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__right__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__right__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__right__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__right__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__right__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__right__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__right__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__right__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__right__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__right__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__right__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__right.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__right__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"CLK_FRQ", &(TOP.Mini_NPU__DOT__up__DOT__CLK_FRQ), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"accum", &(TOP.Mini_NPU__DOT__up__DOT__accum), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"accum_down", &(TOP.Mini_NPU__DOT__up__DOT__accum_down), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"accum_reset", &(TOP.Mini_NPU__DOT__up__DOT__accum_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"accum_up", &(TOP.Mini_NPU__DOT__up__DOT__accum_up), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"activated", &(TOP.Mini_NPU__DOT__up__DOT__activated), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__up__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"cycle", &(TOP.Mini_NPU__DOT__up__DOT__cycle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,23,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"cycle_en", &(TOP.Mini_NPU__DOT__up__DOT__cycle_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"cycle_reset", &(TOP.Mini_NPU__DOT__up__DOT__cycle_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"fire", &(TOP.Mini_NPU__DOT__up__DOT__fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"mn_nextState", &(TOP.Mini_NPU__DOT__up__DOT__mn_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"mn_state", &(TOP.Mini_NPU__DOT__up__DOT__mn_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__up.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__up__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"AeqB", &(TOP.Mini_NPU__DOT__x_axis__DOT__AeqB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"AgtB", &(TOP.Mini_NPU__DOT__x_axis__DOT__AgtB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"AltB", &(TOP.Mini_NPU__DOT__x_axis__DOT__AltB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__x_axis__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"activate1", &(TOP.Mini_NPU__DOT__x_axis__DOT__activate1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"activate2", &(TOP.Mini_NPU__DOT__x_axis__DOT__activate2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"an_nextState", &(TOP.Mini_NPU__DOT__x_axis__DOT__an_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"an_state", &(TOP.Mini_NPU__DOT__x_axis__DOT__an_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__x_axis__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d1_clr", &(TOP.Mini_NPU__DOT__x_axis__DOT__d1_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d1_en", &(TOP.Mini_NPU__DOT__x_axis__DOT__d1_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d2_clr", &(TOP.Mini_NPU__DOT__x_axis__DOT__d2_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d2_en", &(TOP.Mini_NPU__DOT__x_axis__DOT__d2_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d2n_clr", &(TOP.Mini_NPU__DOT__x_axis__DOT__d2n_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"d2n_en", &(TOP.Mini_NPU__DOT__x_axis__DOT__d2n_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"data", &(TOP.Mini_NPU__DOT__x_axis__DOT__data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"data1", &(TOP.Mini_NPU__DOT__x_axis__DOT__data1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"data2", &(TOP.Mini_NPU__DOT__x_axis__DOT__data2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"data2_next", &(TOP.Mini_NPU__DOT__x_axis__DOT__data2_next), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"data_avail", &(TOP.Mini_NPU__DOT__x_axis__DOT__data_avail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__x_axis__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__x_axis.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__x_axis__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"AeqB", &(TOP.Mini_NPU__DOT__y_axis__DOT__AeqB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"AgtB", &(TOP.Mini_NPU__DOT__y_axis__DOT__AgtB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"AltB", &(TOP.Mini_NPU__DOT__y_axis__DOT__AltB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__y_axis__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"activate1", &(TOP.Mini_NPU__DOT__y_axis__DOT__activate1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"activate2", &(TOP.Mini_NPU__DOT__y_axis__DOT__activate2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"an_nextState", &(TOP.Mini_NPU__DOT__y_axis__DOT__an_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"an_state", &(TOP.Mini_NPU__DOT__y_axis__DOT__an_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__y_axis__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d1_clr", &(TOP.Mini_NPU__DOT__y_axis__DOT__d1_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d1_en", &(TOP.Mini_NPU__DOT__y_axis__DOT__d1_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d2_clr", &(TOP.Mini_NPU__DOT__y_axis__DOT__d2_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d2_en", &(TOP.Mini_NPU__DOT__y_axis__DOT__d2_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d2n_clr", &(TOP.Mini_NPU__DOT__y_axis__DOT__d2n_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"d2n_en", &(TOP.Mini_NPU__DOT__y_axis__DOT__d2n_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"data", &(TOP.Mini_NPU__DOT__y_axis__DOT__data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"data1", &(TOP.Mini_NPU__DOT__y_axis__DOT__data1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"data2", &(TOP.Mini_NPU__DOT__y_axis__DOT__data2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"data2_next", &(TOP.Mini_NPU__DOT__y_axis__DOT__data2_next), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"data_avail", &(TOP.Mini_NPU__DOT__y_axis__DOT__data_avail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__y_axis__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__y_axis.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__y_axis__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"AeqB", &(TOP.Mini_NPU__DOT__z_axis__DOT__AeqB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"AgtB", &(TOP.Mini_NPU__DOT__z_axis__DOT__AgtB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"AltB", &(TOP.Mini_NPU__DOT__z_axis__DOT__AltB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"abort", &(TOP.Mini_NPU__DOT__z_axis__DOT__abort), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"activate1", &(TOP.Mini_NPU__DOT__z_axis__DOT__activate1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"activate2", &(TOP.Mini_NPU__DOT__z_axis__DOT__activate2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"an_nextState", &(TOP.Mini_NPU__DOT__z_axis__DOT__an_nextState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"an_state", &(TOP.Mini_NPU__DOT__z_axis__DOT__an_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"clock", &(TOP.Mini_NPU__DOT__z_axis__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d1_clr", &(TOP.Mini_NPU__DOT__z_axis__DOT__d1_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d1_en", &(TOP.Mini_NPU__DOT__z_axis__DOT__d1_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d2_clr", &(TOP.Mini_NPU__DOT__z_axis__DOT__d2_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d2_en", &(TOP.Mini_NPU__DOT__z_axis__DOT__d2_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d2n_clr", &(TOP.Mini_NPU__DOT__z_axis__DOT__d2n_clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"d2n_en", &(TOP.Mini_NPU__DOT__z_axis__DOT__d2n_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"data", &(TOP.Mini_NPU__DOT__z_axis__DOT__data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"data1", &(TOP.Mini_NPU__DOT__z_axis__DOT__data1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"data2", &(TOP.Mini_NPU__DOT__z_axis__DOT__data2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"data2_next", &(TOP.Mini_NPU__DOT__z_axis__DOT__data2_next), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"data_avail", &(TOP.Mini_NPU__DOT__z_axis__DOT__data_avail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"reset", &(TOP.Mini_NPU__DOT__z_axis__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_Mini_NPU__z_axis.varInsert(__Vfinal,"stop", &(TOP.Mini_NPU__DOT__z_axis__DOT__stop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"LEDs", &(TOP.LEDs), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"SCL", &(TOP.SCL), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"SDA", &(TOP.SDA), false, VLVT_UINT8,VLVD_INOUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"SDA_in", &(TOP.SDA_in), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"clock", &(TOP.clock), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"reset", &(TOP.reset), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"start", &(TOP.start), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"stop", &(TOP.stop), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
    }
}
