// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"start",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"SDA_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"SDA",-1, VerilatedTraceSigDirection::INOUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"SCL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"LEDs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("Mini_NPU", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+9,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"start",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"SDA_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"SDA",-1, VerilatedTraceSigDirection::INOUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"SCL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"LEDs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+17,0,"write_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"data_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"read_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"abort",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"poll",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"data_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"data_avail",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+25,0,"X_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+26,0,"Y_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+27,0,"Z_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+28,0,"left_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"right_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"back_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"forward_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"down_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"up_activated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"left_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"right_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"back_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"forward_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"down_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"up_fired",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"fired_array",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("back", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+41,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+45,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+46,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+51,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+52,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+53,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("down", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+55,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+57,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+58,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+59,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+60,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+63,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+65,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+66,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+67,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("forward", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+69,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+73,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+74,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+77,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+78,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+79,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+80,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+81,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("i2c_m", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+83,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"SDA_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"poll",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"data_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"SDA",-1, VerilatedTraceSigDirection::INOUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"SCL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"write_done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+93,0,"data_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"read_done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"abort",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"data_avail",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+97,0,"X_DATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+98,0,"Y_DATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+99,0,"Z_DATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+100,0,"SDA_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+101,0,"sda_out_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"SCL_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"scl_out_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+104,0,"ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+105,0,"addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+106,0,"sub_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+107,0,"sad_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+108,0,"sad_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+109,0,"INT_SOURCE_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+110,0,"DATAX0_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+111,0,"FIFO_CTL_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+112,0,"FIFO_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+113,0,"INT_SOURCE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+114,0,"X0_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+115,0,"X1_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+116,0,"Y0_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+117,0,"Y1_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+118,0,"Z0_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+119,0,"Z1_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+120,0,"iteration",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+121,0,"count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+122,0,"data_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+123,0,"i_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"i_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"count_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"count_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"data_count_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"data_count_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"shift_in_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"shift_clr_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"shift_in_x0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"shift_in_x1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"shift_clr_x0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"shift_clr_x1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"shift_in_y0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"shift_in_y1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"shift_clr_y0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"shift_clr_y1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"shift_in_z0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"shift_in_z1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"shift_clr_z0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"shift_clr_z1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+144,0,"i2c_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i2c_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->pushPrefix("sipo_source", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+146,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+151,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_x0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+152,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+157,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_x1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+158,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+163,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_y0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+164,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+168,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+169,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_y1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+170,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+175,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_z0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+176,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+179,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+181,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("sipo_z1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+182,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+185,0,"shift_clr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+186,0,"serial_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+187,0,"Q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("led_c", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+188,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+190,0,"fired_array",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+191,0,"LEDs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+192,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+193,0,"count_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+194,0,"count_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"count_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"led_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"led_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+198,0,"fired_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+199,0,"count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 24,0);
    tracep->declBit(c+200,0,"led_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+201,0,"led_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("left", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+202,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+203,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+204,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+206,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+207,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+210,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+211,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+212,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+213,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+214,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ph", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+216,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+217,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+218,0,"start",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"write_done",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"data_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"read_done",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+223,0,"abort",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"poll",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"data_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"write_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"poll_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"data_read_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+230,0,"ph_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+231,0,"ph_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("right", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+232,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+233,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+236,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+237,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+238,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+243,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+244,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("up", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+246,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+248,0,"activated",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"fire",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+250,0,"CLK_FRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBit(c+251,0,"cycle_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+252,0,"cycle_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+253,0,"accum_up",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"accum_down",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"accum_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+256,0,"cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+257,0,"accum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+258,0,"mn_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+259,0,"mn_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("x_axis", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+260,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+261,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+262,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+263,0,"data_avail",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+264,0,"abort",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+265,0,"data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+266,0,"activate1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"activate2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+268,0,"AltB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"AeqB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+270,0,"AgtB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+271,0,"d1_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+272,0,"d2_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+273,0,"d2n_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+274,0,"d1_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+275,0,"d2_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"d2n_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+277,0,"data1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+278,0,"data2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+279,0,"data2_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+280,0,"an_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+281,0,"an_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("y_axis", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+282,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+283,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+284,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"data_avail",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+286,0,"abort",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+287,0,"data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+288,0,"activate1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+289,0,"activate2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+290,0,"AltB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+291,0,"AeqB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+292,0,"AgtB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"d1_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+294,0,"d2_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+295,0,"d2n_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+296,0,"d1_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+297,0,"d2_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+298,0,"d2n_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+299,0,"data1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+300,0,"data2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+301,0,"data2_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+302,0,"an_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+303,0,"an_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("z_axis", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+304,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+305,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+306,0,"stop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+307,0,"data_avail",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+308,0,"abort",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+309,0,"data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+310,0,"activate1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+311,0,"activate2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+312,0,"AltB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+313,0,"AeqB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+314,0,"AgtB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+315,0,"d1_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+316,0,"d2_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+317,0,"d2n_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+318,0,"d1_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+319,0,"d2_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+320,0,"d2n_clr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+321,0,"data1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+322,0,"data2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+323,0,"data2_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+324,0,"an_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+325,0,"an_nextState",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->clock));
    bufp->fullBit(oldp+2,(vlSelf->reset));
    bufp->fullBit(oldp+3,(vlSelf->start));
    bufp->fullBit(oldp+4,(vlSelf->stop));
    bufp->fullBit(oldp+5,(vlSelf->SDA_in));
    bufp->fullBit(oldp+6,(vlSelf->SDA));
    bufp->fullBit(oldp+7,(vlSelf->SCL));
    bufp->fullCData(oldp+8,(vlSelf->LEDs),8);
    bufp->fullBit(oldp+9,(vlSelf->Mini_NPU__DOT__clock));
    bufp->fullBit(oldp+10,(vlSelf->Mini_NPU__DOT__reset));
    bufp->fullBit(oldp+11,(vlSelf->Mini_NPU__DOT__start));
    bufp->fullBit(oldp+12,(vlSelf->Mini_NPU__DOT__stop));
    bufp->fullBit(oldp+13,(vlSelf->Mini_NPU__DOT__SDA_in));
    bufp->fullBit(oldp+14,(vlSelf->Mini_NPU__DOT__SDA));
    bufp->fullBit(oldp+15,(vlSelf->Mini_NPU__DOT__SCL));
    bufp->fullCData(oldp+16,(vlSelf->Mini_NPU__DOT__LEDs),8);
    bufp->fullBit(oldp+17,(vlSelf->Mini_NPU__DOT__write_done));
    bufp->fullBit(oldp+18,(vlSelf->Mini_NPU__DOT__data_ready));
    bufp->fullBit(oldp+19,(vlSelf->Mini_NPU__DOT__read_done));
    bufp->fullBit(oldp+20,(vlSelf->Mini_NPU__DOT__abort));
    bufp->fullBit(oldp+21,(vlSelf->Mini_NPU__DOT__write));
    bufp->fullBit(oldp+22,(vlSelf->Mini_NPU__DOT__poll));
    bufp->fullBit(oldp+23,(vlSelf->Mini_NPU__DOT__data_read));
    bufp->fullBit(oldp+24,(vlSelf->Mini_NPU__DOT__data_avail));
    bufp->fullSData(oldp+25,(vlSelf->Mini_NPU__DOT__X_DATA),16);
    bufp->fullSData(oldp+26,(vlSelf->Mini_NPU__DOT__Y_DATA),16);
    bufp->fullSData(oldp+27,(vlSelf->Mini_NPU__DOT__Z_DATA),16);
    bufp->fullBit(oldp+28,(vlSelf->Mini_NPU__DOT__left_activated));
    bufp->fullBit(oldp+29,(vlSelf->Mini_NPU__DOT__right_activated));
    bufp->fullBit(oldp+30,(vlSelf->Mini_NPU__DOT__back_activated));
    bufp->fullBit(oldp+31,(vlSelf->Mini_NPU__DOT__forward_activated));
    bufp->fullBit(oldp+32,(vlSelf->Mini_NPU__DOT__down_activated));
    bufp->fullBit(oldp+33,(vlSelf->Mini_NPU__DOT__up_activated));
    bufp->fullBit(oldp+34,(vlSelf->Mini_NPU__DOT__left_fired));
    bufp->fullBit(oldp+35,(vlSelf->Mini_NPU__DOT__right_fired));
    bufp->fullBit(oldp+36,(vlSelf->Mini_NPU__DOT__back_fired));
    bufp->fullBit(oldp+37,(vlSelf->Mini_NPU__DOT__forward_fired));
    bufp->fullBit(oldp+38,(vlSelf->Mini_NPU__DOT__down_fired));
    bufp->fullBit(oldp+39,(vlSelf->Mini_NPU__DOT__up_fired));
    bufp->fullCData(oldp+40,(vlSelf->Mini_NPU__DOT__fired_array),8);
    bufp->fullBit(oldp+41,(vlSelf->Mini_NPU__DOT__back__DOT__clock));
    bufp->fullBit(oldp+42,(vlSelf->Mini_NPU__DOT__back__DOT__reset));
    bufp->fullBit(oldp+43,(vlSelf->Mini_NPU__DOT__back__DOT__activated));
    bufp->fullBit(oldp+44,(vlSelf->Mini_NPU__DOT__back__DOT__fire));
    bufp->fullIData(oldp+45,(vlSelf->Mini_NPU__DOT__back__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+46,(vlSelf->Mini_NPU__DOT__back__DOT__cycle_en));
    bufp->fullBit(oldp+47,(vlSelf->Mini_NPU__DOT__back__DOT__cycle_reset));
    bufp->fullBit(oldp+48,(vlSelf->Mini_NPU__DOT__back__DOT__accum_up));
    bufp->fullBit(oldp+49,(vlSelf->Mini_NPU__DOT__back__DOT__accum_down));
    bufp->fullBit(oldp+50,(vlSelf->Mini_NPU__DOT__back__DOT__accum_reset));
    bufp->fullIData(oldp+51,(vlSelf->Mini_NPU__DOT__back__DOT__cycle),24);
    bufp->fullCData(oldp+52,(vlSelf->Mini_NPU__DOT__back__DOT__accum),7);
    bufp->fullBit(oldp+53,(vlSelf->Mini_NPU__DOT__back__DOT__mn_state));
    bufp->fullBit(oldp+54,(vlSelf->Mini_NPU__DOT__back__DOT__mn_nextState));
    bufp->fullBit(oldp+55,(vlSelf->Mini_NPU__DOT__down__DOT__clock));
    bufp->fullBit(oldp+56,(vlSelf->Mini_NPU__DOT__down__DOT__reset));
    bufp->fullBit(oldp+57,(vlSelf->Mini_NPU__DOT__down__DOT__activated));
    bufp->fullBit(oldp+58,(vlSelf->Mini_NPU__DOT__down__DOT__fire));
    bufp->fullIData(oldp+59,(vlSelf->Mini_NPU__DOT__down__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+60,(vlSelf->Mini_NPU__DOT__down__DOT__cycle_en));
    bufp->fullBit(oldp+61,(vlSelf->Mini_NPU__DOT__down__DOT__cycle_reset));
    bufp->fullBit(oldp+62,(vlSelf->Mini_NPU__DOT__down__DOT__accum_up));
    bufp->fullBit(oldp+63,(vlSelf->Mini_NPU__DOT__down__DOT__accum_down));
    bufp->fullBit(oldp+64,(vlSelf->Mini_NPU__DOT__down__DOT__accum_reset));
    bufp->fullIData(oldp+65,(vlSelf->Mini_NPU__DOT__down__DOT__cycle),24);
    bufp->fullCData(oldp+66,(vlSelf->Mini_NPU__DOT__down__DOT__accum),7);
    bufp->fullBit(oldp+67,(vlSelf->Mini_NPU__DOT__down__DOT__mn_state));
    bufp->fullBit(oldp+68,(vlSelf->Mini_NPU__DOT__down__DOT__mn_nextState));
    bufp->fullBit(oldp+69,(vlSelf->Mini_NPU__DOT__forward__DOT__clock));
    bufp->fullBit(oldp+70,(vlSelf->Mini_NPU__DOT__forward__DOT__reset));
    bufp->fullBit(oldp+71,(vlSelf->Mini_NPU__DOT__forward__DOT__activated));
    bufp->fullBit(oldp+72,(vlSelf->Mini_NPU__DOT__forward__DOT__fire));
    bufp->fullIData(oldp+73,(vlSelf->Mini_NPU__DOT__forward__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+74,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle_en));
    bufp->fullBit(oldp+75,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle_reset));
    bufp->fullBit(oldp+76,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_up));
    bufp->fullBit(oldp+77,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_down));
    bufp->fullBit(oldp+78,(vlSelf->Mini_NPU__DOT__forward__DOT__accum_reset));
    bufp->fullIData(oldp+79,(vlSelf->Mini_NPU__DOT__forward__DOT__cycle),24);
    bufp->fullCData(oldp+80,(vlSelf->Mini_NPU__DOT__forward__DOT__accum),7);
    bufp->fullBit(oldp+81,(vlSelf->Mini_NPU__DOT__forward__DOT__mn_state));
    bufp->fullBit(oldp+82,(vlSelf->Mini_NPU__DOT__forward__DOT__mn_nextState));
    bufp->fullBit(oldp+83,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__clock));
    bufp->fullBit(oldp+84,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__reset));
    bufp->fullBit(oldp+85,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__stop));
    bufp->fullBit(oldp+86,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA_in));
    bufp->fullBit(oldp+87,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__write));
    bufp->fullBit(oldp+88,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__poll));
    bufp->fullBit(oldp+89,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_read));
    bufp->fullBit(oldp+90,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA));
    bufp->fullBit(oldp+91,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SCL));
    bufp->fullBit(oldp+92,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__write_done));
    bufp->fullBit(oldp+93,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_ready));
    bufp->fullBit(oldp+94,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__read_done));
    bufp->fullBit(oldp+95,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__abort));
    bufp->fullBit(oldp+96,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_avail));
    bufp->fullSData(oldp+97,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X_DATA),16);
    bufp->fullSData(oldp+98,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y_DATA),16);
    bufp->fullSData(oldp+99,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z_DATA),16);
    bufp->fullBit(oldp+100,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SDA_out));
    bufp->fullBit(oldp+101,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sda_out_en));
    bufp->fullBit(oldp+102,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__SCL_out));
    bufp->fullBit(oldp+103,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__scl_out_en));
    bufp->fullCData(oldp+104,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__ADDR),8);
    bufp->fullCData(oldp+105,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__addr),8);
    bufp->fullCData(oldp+106,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sub_addr),8);
    bufp->fullCData(oldp+107,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sad_w),8);
    bufp->fullCData(oldp+108,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sad_r),8);
    bufp->fullCData(oldp+109,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE_addr),8);
    bufp->fullCData(oldp+110,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__DATAX0_addr),8);
    bufp->fullCData(oldp+111,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__FIFO_CTL_addr),8);
    bufp->fullCData(oldp+112,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__FIFO_DATA),8);
    bufp->fullCData(oldp+113,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__INT_SOURCE),8);
    bufp->fullCData(oldp+114,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X0_DATA),8);
    bufp->fullCData(oldp+115,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__X1_DATA),8);
    bufp->fullCData(oldp+116,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y0_DATA),8);
    bufp->fullCData(oldp+117,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Y1_DATA),8);
    bufp->fullCData(oldp+118,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z0_DATA),8);
    bufp->fullCData(oldp+119,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__Z1_DATA),8);
    bufp->fullCData(oldp+120,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__iteration),2);
    bufp->fullCData(oldp+121,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count),4);
    bufp->fullCData(oldp+122,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count),6);
    bufp->fullBit(oldp+123,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i_up));
    bufp->fullBit(oldp+124,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i_clr));
    bufp->fullBit(oldp+125,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count_en));
    bufp->fullBit(oldp+126,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__count_reset));
    bufp->fullBit(oldp+127,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count_en));
    bufp->fullBit(oldp+128,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data_count_reset));
    bufp->fullBit(oldp+129,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_s));
    bufp->fullBit(oldp+130,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_s));
    bufp->fullBit(oldp+131,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_x0));
    bufp->fullBit(oldp+132,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_x1));
    bufp->fullBit(oldp+133,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_x0));
    bufp->fullBit(oldp+134,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_x1));
    bufp->fullBit(oldp+135,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_y0));
    bufp->fullBit(oldp+136,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_y1));
    bufp->fullBit(oldp+137,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_y0));
    bufp->fullBit(oldp+138,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_y1));
    bufp->fullBit(oldp+139,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_z0));
    bufp->fullBit(oldp+140,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_in_z1));
    bufp->fullBit(oldp+141,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_z0));
    bufp->fullBit(oldp+142,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__shift_clr_z1));
    bufp->fullBit(oldp+143,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__data));
    bufp->fullCData(oldp+144,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i2c_state),4);
    bufp->fullCData(oldp+145,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__i2c_nextState),4);
    bufp->fullBit(oldp+146,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__clock));
    bufp->fullBit(oldp+147,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__reset));
    bufp->fullBit(oldp+148,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__en));
    bufp->fullBit(oldp+149,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__shift_clr));
    bufp->fullBit(oldp+150,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__serial_bit));
    bufp->fullCData(oldp+151,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_source__DOT__Q),8);
    bufp->fullBit(oldp+152,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__clock));
    bufp->fullBit(oldp+153,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__reset));
    bufp->fullBit(oldp+154,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__en));
    bufp->fullBit(oldp+155,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__shift_clr));
    bufp->fullBit(oldp+156,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__serial_bit));
    bufp->fullCData(oldp+157,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x0__DOT__Q),8);
    bufp->fullBit(oldp+158,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__clock));
    bufp->fullBit(oldp+159,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__reset));
    bufp->fullBit(oldp+160,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__en));
    bufp->fullBit(oldp+161,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__shift_clr));
    bufp->fullBit(oldp+162,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__serial_bit));
    bufp->fullCData(oldp+163,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_x1__DOT__Q),8);
    bufp->fullBit(oldp+164,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__clock));
    bufp->fullBit(oldp+165,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__reset));
    bufp->fullBit(oldp+166,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__en));
    bufp->fullBit(oldp+167,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__shift_clr));
    bufp->fullBit(oldp+168,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__serial_bit));
    bufp->fullCData(oldp+169,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y0__DOT__Q),8);
    bufp->fullBit(oldp+170,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__clock));
    bufp->fullBit(oldp+171,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__reset));
    bufp->fullBit(oldp+172,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__en));
    bufp->fullBit(oldp+173,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__shift_clr));
    bufp->fullBit(oldp+174,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__serial_bit));
    bufp->fullCData(oldp+175,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_y1__DOT__Q),8);
    bufp->fullBit(oldp+176,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__clock));
    bufp->fullBit(oldp+177,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__reset));
    bufp->fullBit(oldp+178,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__en));
    bufp->fullBit(oldp+179,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__shift_clr));
    bufp->fullBit(oldp+180,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__serial_bit));
    bufp->fullCData(oldp+181,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z0__DOT__Q),8);
    bufp->fullBit(oldp+182,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__clock));
    bufp->fullBit(oldp+183,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__reset));
    bufp->fullBit(oldp+184,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__en));
    bufp->fullBit(oldp+185,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__shift_clr));
    bufp->fullBit(oldp+186,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__serial_bit));
    bufp->fullCData(oldp+187,(vlSelf->Mini_NPU__DOT__i2c_m__DOT__sipo_z1__DOT__Q),8);
    bufp->fullBit(oldp+188,(vlSelf->Mini_NPU__DOT__led_c__DOT__clock));
    bufp->fullBit(oldp+189,(vlSelf->Mini_NPU__DOT__led_c__DOT__reset));
    bufp->fullCData(oldp+190,(vlSelf->Mini_NPU__DOT__led_c__DOT__fired_array),8);
    bufp->fullCData(oldp+191,(vlSelf->Mini_NPU__DOT__led_c__DOT__LEDs),8);
    bufp->fullIData(oldp+192,(vlSelf->Mini_NPU__DOT__led_c__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+193,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_done));
    bufp->fullBit(oldp+194,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_down));
    bufp->fullBit(oldp+195,(vlSelf->Mini_NPU__DOT__led_c__DOT__count_reset));
    bufp->fullBit(oldp+196,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_en));
    bufp->fullBit(oldp+197,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_reset));
    bufp->fullBit(oldp+198,(vlSelf->Mini_NPU__DOT__led_c__DOT__fired_clr));
    bufp->fullIData(oldp+199,(vlSelf->Mini_NPU__DOT__led_c__DOT__count),25);
    bufp->fullBit(oldp+200,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_state));
    bufp->fullBit(oldp+201,(vlSelf->Mini_NPU__DOT__led_c__DOT__led_nextState));
    bufp->fullBit(oldp+202,(vlSelf->Mini_NPU__DOT__left__DOT__clock));
    bufp->fullBit(oldp+203,(vlSelf->Mini_NPU__DOT__left__DOT__reset));
    bufp->fullBit(oldp+204,(vlSelf->Mini_NPU__DOT__left__DOT__activated));
    bufp->fullBit(oldp+205,(vlSelf->Mini_NPU__DOT__left__DOT__fire));
    bufp->fullIData(oldp+206,(vlSelf->Mini_NPU__DOT__left__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+207,(vlSelf->Mini_NPU__DOT__left__DOT__cycle_en));
    bufp->fullBit(oldp+208,(vlSelf->Mini_NPU__DOT__left__DOT__cycle_reset));
    bufp->fullBit(oldp+209,(vlSelf->Mini_NPU__DOT__left__DOT__accum_up));
    bufp->fullBit(oldp+210,(vlSelf->Mini_NPU__DOT__left__DOT__accum_down));
    bufp->fullBit(oldp+211,(vlSelf->Mini_NPU__DOT__left__DOT__accum_reset));
    bufp->fullIData(oldp+212,(vlSelf->Mini_NPU__DOT__left__DOT__cycle),24);
    bufp->fullCData(oldp+213,(vlSelf->Mini_NPU__DOT__left__DOT__accum),7);
    bufp->fullBit(oldp+214,(vlSelf->Mini_NPU__DOT__left__DOT__mn_state));
    bufp->fullBit(oldp+215,(vlSelf->Mini_NPU__DOT__left__DOT__mn_nextState));
    bufp->fullBit(oldp+216,(vlSelf->Mini_NPU__DOT__ph__DOT__clock));
    bufp->fullBit(oldp+217,(vlSelf->Mini_NPU__DOT__ph__DOT__reset));
    bufp->fullBit(oldp+218,(vlSelf->Mini_NPU__DOT__ph__DOT__start));
    bufp->fullBit(oldp+219,(vlSelf->Mini_NPU__DOT__ph__DOT__stop));
    bufp->fullBit(oldp+220,(vlSelf->Mini_NPU__DOT__ph__DOT__write_done));
    bufp->fullBit(oldp+221,(vlSelf->Mini_NPU__DOT__ph__DOT__data_ready));
    bufp->fullBit(oldp+222,(vlSelf->Mini_NPU__DOT__ph__DOT__read_done));
    bufp->fullBit(oldp+223,(vlSelf->Mini_NPU__DOT__ph__DOT__abort));
    bufp->fullBit(oldp+224,(vlSelf->Mini_NPU__DOT__ph__DOT__write));
    bufp->fullBit(oldp+225,(vlSelf->Mini_NPU__DOT__ph__DOT__poll));
    bufp->fullBit(oldp+226,(vlSelf->Mini_NPU__DOT__ph__DOT__data_read));
    bufp->fullBit(oldp+227,(vlSelf->Mini_NPU__DOT__ph__DOT__write_en));
    bufp->fullBit(oldp+228,(vlSelf->Mini_NPU__DOT__ph__DOT__poll_en));
    bufp->fullBit(oldp+229,(vlSelf->Mini_NPU__DOT__ph__DOT__data_read_en));
    bufp->fullCData(oldp+230,(vlSelf->Mini_NPU__DOT__ph__DOT__ph_state),2);
    bufp->fullCData(oldp+231,(vlSelf->Mini_NPU__DOT__ph__DOT__ph_nextState),2);
    bufp->fullBit(oldp+232,(vlSelf->Mini_NPU__DOT__right__DOT__clock));
    bufp->fullBit(oldp+233,(vlSelf->Mini_NPU__DOT__right__DOT__reset));
    bufp->fullBit(oldp+234,(vlSelf->Mini_NPU__DOT__right__DOT__activated));
    bufp->fullBit(oldp+235,(vlSelf->Mini_NPU__DOT__right__DOT__fire));
    bufp->fullIData(oldp+236,(vlSelf->Mini_NPU__DOT__right__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+237,(vlSelf->Mini_NPU__DOT__right__DOT__cycle_en));
    bufp->fullBit(oldp+238,(vlSelf->Mini_NPU__DOT__right__DOT__cycle_reset));
    bufp->fullBit(oldp+239,(vlSelf->Mini_NPU__DOT__right__DOT__accum_up));
    bufp->fullBit(oldp+240,(vlSelf->Mini_NPU__DOT__right__DOT__accum_down));
    bufp->fullBit(oldp+241,(vlSelf->Mini_NPU__DOT__right__DOT__accum_reset));
    bufp->fullIData(oldp+242,(vlSelf->Mini_NPU__DOT__right__DOT__cycle),24);
    bufp->fullCData(oldp+243,(vlSelf->Mini_NPU__DOT__right__DOT__accum),7);
    bufp->fullBit(oldp+244,(vlSelf->Mini_NPU__DOT__right__DOT__mn_state));
    bufp->fullBit(oldp+245,(vlSelf->Mini_NPU__DOT__right__DOT__mn_nextState));
    bufp->fullBit(oldp+246,(vlSelf->Mini_NPU__DOT__up__DOT__clock));
    bufp->fullBit(oldp+247,(vlSelf->Mini_NPU__DOT__up__DOT__reset));
    bufp->fullBit(oldp+248,(vlSelf->Mini_NPU__DOT__up__DOT__activated));
    bufp->fullBit(oldp+249,(vlSelf->Mini_NPU__DOT__up__DOT__fire));
    bufp->fullIData(oldp+250,(vlSelf->Mini_NPU__DOT__up__DOT__CLK_FRQ),24);
    bufp->fullBit(oldp+251,(vlSelf->Mini_NPU__DOT__up__DOT__cycle_en));
    bufp->fullBit(oldp+252,(vlSelf->Mini_NPU__DOT__up__DOT__cycle_reset));
    bufp->fullBit(oldp+253,(vlSelf->Mini_NPU__DOT__up__DOT__accum_up));
    bufp->fullBit(oldp+254,(vlSelf->Mini_NPU__DOT__up__DOT__accum_down));
    bufp->fullBit(oldp+255,(vlSelf->Mini_NPU__DOT__up__DOT__accum_reset));
    bufp->fullIData(oldp+256,(vlSelf->Mini_NPU__DOT__up__DOT__cycle),24);
    bufp->fullCData(oldp+257,(vlSelf->Mini_NPU__DOT__up__DOT__accum),7);
    bufp->fullBit(oldp+258,(vlSelf->Mini_NPU__DOT__up__DOT__mn_state));
    bufp->fullBit(oldp+259,(vlSelf->Mini_NPU__DOT__up__DOT__mn_nextState));
    bufp->fullBit(oldp+260,(vlSelf->Mini_NPU__DOT__x_axis__DOT__clock));
    bufp->fullBit(oldp+261,(vlSelf->Mini_NPU__DOT__x_axis__DOT__reset));
    bufp->fullBit(oldp+262,(vlSelf->Mini_NPU__DOT__x_axis__DOT__stop));
    bufp->fullBit(oldp+263,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data_avail));
    bufp->fullBit(oldp+264,(vlSelf->Mini_NPU__DOT__x_axis__DOT__abort));
    bufp->fullSData(oldp+265,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data),16);
    bufp->fullBit(oldp+266,(vlSelf->Mini_NPU__DOT__x_axis__DOT__activate1));
    bufp->fullBit(oldp+267,(vlSelf->Mini_NPU__DOT__x_axis__DOT__activate2));
    bufp->fullBit(oldp+268,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AltB));
    bufp->fullBit(oldp+269,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AeqB));
    bufp->fullBit(oldp+270,(vlSelf->Mini_NPU__DOT__x_axis__DOT__AgtB));
    bufp->fullBit(oldp+271,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d1_en));
    bufp->fullBit(oldp+272,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2_en));
    bufp->fullBit(oldp+273,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2n_en));
    bufp->fullBit(oldp+274,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d1_clr));
    bufp->fullBit(oldp+275,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2_clr));
    bufp->fullBit(oldp+276,(vlSelf->Mini_NPU__DOT__x_axis__DOT__d2n_clr));
    bufp->fullSData(oldp+277,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data1),16);
    bufp->fullSData(oldp+278,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data2),16);
    bufp->fullSData(oldp+279,(vlSelf->Mini_NPU__DOT__x_axis__DOT__data2_next),16);
    bufp->fullCData(oldp+280,(vlSelf->Mini_NPU__DOT__x_axis__DOT__an_state),3);
    bufp->fullCData(oldp+281,(vlSelf->Mini_NPU__DOT__x_axis__DOT__an_nextState),3);
    bufp->fullBit(oldp+282,(vlSelf->Mini_NPU__DOT__y_axis__DOT__clock));
    bufp->fullBit(oldp+283,(vlSelf->Mini_NPU__DOT__y_axis__DOT__reset));
    bufp->fullBit(oldp+284,(vlSelf->Mini_NPU__DOT__y_axis__DOT__stop));
    bufp->fullBit(oldp+285,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data_avail));
    bufp->fullBit(oldp+286,(vlSelf->Mini_NPU__DOT__y_axis__DOT__abort));
    bufp->fullSData(oldp+287,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data),16);
    bufp->fullBit(oldp+288,(vlSelf->Mini_NPU__DOT__y_axis__DOT__activate1));
    bufp->fullBit(oldp+289,(vlSelf->Mini_NPU__DOT__y_axis__DOT__activate2));
    bufp->fullBit(oldp+290,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AltB));
    bufp->fullBit(oldp+291,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AeqB));
    bufp->fullBit(oldp+292,(vlSelf->Mini_NPU__DOT__y_axis__DOT__AgtB));
    bufp->fullBit(oldp+293,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d1_en));
    bufp->fullBit(oldp+294,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2_en));
    bufp->fullBit(oldp+295,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2n_en));
    bufp->fullBit(oldp+296,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d1_clr));
    bufp->fullBit(oldp+297,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2_clr));
    bufp->fullBit(oldp+298,(vlSelf->Mini_NPU__DOT__y_axis__DOT__d2n_clr));
    bufp->fullSData(oldp+299,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data1),16);
    bufp->fullSData(oldp+300,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data2),16);
    bufp->fullSData(oldp+301,(vlSelf->Mini_NPU__DOT__y_axis__DOT__data2_next),16);
    bufp->fullCData(oldp+302,(vlSelf->Mini_NPU__DOT__y_axis__DOT__an_state),3);
    bufp->fullCData(oldp+303,(vlSelf->Mini_NPU__DOT__y_axis__DOT__an_nextState),3);
    bufp->fullBit(oldp+304,(vlSelf->Mini_NPU__DOT__z_axis__DOT__clock));
    bufp->fullBit(oldp+305,(vlSelf->Mini_NPU__DOT__z_axis__DOT__reset));
    bufp->fullBit(oldp+306,(vlSelf->Mini_NPU__DOT__z_axis__DOT__stop));
    bufp->fullBit(oldp+307,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data_avail));
    bufp->fullBit(oldp+308,(vlSelf->Mini_NPU__DOT__z_axis__DOT__abort));
    bufp->fullSData(oldp+309,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data),16);
    bufp->fullBit(oldp+310,(vlSelf->Mini_NPU__DOT__z_axis__DOT__activate1));
    bufp->fullBit(oldp+311,(vlSelf->Mini_NPU__DOT__z_axis__DOT__activate2));
    bufp->fullBit(oldp+312,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AltB));
    bufp->fullBit(oldp+313,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AeqB));
    bufp->fullBit(oldp+314,(vlSelf->Mini_NPU__DOT__z_axis__DOT__AgtB));
    bufp->fullBit(oldp+315,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d1_en));
    bufp->fullBit(oldp+316,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2_en));
    bufp->fullBit(oldp+317,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2n_en));
    bufp->fullBit(oldp+318,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d1_clr));
    bufp->fullBit(oldp+319,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2_clr));
    bufp->fullBit(oldp+320,(vlSelf->Mini_NPU__DOT__z_axis__DOT__d2n_clr));
    bufp->fullSData(oldp+321,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data1),16);
    bufp->fullSData(oldp+322,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data2),16);
    bufp->fullSData(oldp+323,(vlSelf->Mini_NPU__DOT__z_axis__DOT__data2_next),16);
    bufp->fullCData(oldp+324,(vlSelf->Mini_NPU__DOT__z_axis__DOT__an_state),3);
    bufp->fullCData(oldp+325,(vlSelf->Mini_NPU__DOT__z_axis__DOT__an_nextState),3);
}
